"""
Django settings for MyBlog project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.contrib import messages

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!6pf6ei&6bv!bs3*35a+%)ugtzki%(-3kz=!fsb-&rf=$5qmit'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Site',
    'User',
    'social_django',
    'pyuploadcare.dj',
    'tinymce',
    'froala_editor',
]

AUTHENTICATION_BACKENDS = [
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware'
]

ROOT_URLCONF = 'MyBlog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyBlog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
###
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'BITSHUB',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }  ###
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = 'static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'bitshub001@gmail.com'
EMAIL_HOST_PASSWORD = '123AbduL456'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

UPLOADCARE = {
    'pub_key': '760dabb2b41e4180f230',
    'secret': 'd8615cbee51e9cada5b3',
}

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# FROALA_EDITOR_THIRD_PARTY = ['image_aviary', 'spell_checker', 'font_awesome', 'embedly']
# FROALA_EDITOR_PLUGINS = ('align', 'char_counter', 'code_beautifier', 'code_view', 'colors', 'draggable', 'emoticons',
#                          'entities', 'file','emoticons', 'font_family', 'font_size', 'fullscreen', 'image_manager', 'image',
#                          'inline_style',
#                          'line_breaker', 'link', 'html', 'lists', 'paragraph_format', 'paragraph_style', 'quick_insert',
#                          'quote', 'save', 'table',
#                          'url', 'video')
#
# TINYMCE_JS_URL = "https://cdn.tiny.cloud/1/kanciud9vht1hdzo6kfjrlb2ellb9bwu79cuosi7a3dxitmp/tinymce/5/tinymce.min.js"
TINYMCE_SPELLCHECKER = True
TINYMCE_DEFAULT_CONFIG = {
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'silver',
    'skin': 'oxide',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code imagetools lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print quickbars hr
            anchor pagebreak importcss fullpage emoticons advlist autoresize tabfocus
            ''',
    'toolbar1': '''
            fullscreen fullpage importcss preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright quickbars|
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media insertfile| codesample |autoresize tabfocus 
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'image_caption': True,
    'image_advtab': True,
    'contextmenu': 'formats | link media emoticons',
    'menubar': True,
    'statusbar': True,
    'height': 500,
}
TINYMCE_EXTRA_MEDIA = {'css': {
    'all': ['css/style.css', 'css/blog-create/style.css', 'css/blog-create/responsive.css'],
}
}

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
    messages.SUCCESS: 'success'
}

SOCIAL_AUTH_GITHUB_KEY = 'f7757280f5fbc4b84739'
SOCIAL_AUTH_GITHUB_SECRET = '4466a06d14bdf487956e0b40a91d159ed37f8ce0'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '814129464384-1j57h41b18h30bof3m85l043e267rd9m.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'eFKiiqHo3U3yV14hEXJFPqO3'

SOCIAL_AUTH_FACEBOOK_KEY = '399588224736200'
SOCIAL_AUTH_FACEBOOK_SECRET = '55371136f78db90af6aa521f534c137b'
